name: test_and_deploy_docker_multi-service-app
on:
  push:
    branches:
      - master

jobs:
  test:
    name: test_before_deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout_code
        uses: actions/checkout@v3

      - name: docker_build
        run: docker build -t youngermm/multi-service-app-client -f ./multi-service-app-client/Dockerfile.dev ./multi-service-app-client

      - name: test_application
        run: docker run -e CI=true youngermm/multi-service-app-client npm test

  docker:
    name: docker_build_push
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: docker_login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build client
        run: docker build -t youngermm/multi-service-app-client ./multi-service-app-client

      - name: Push client
        run: docker push youngermm/multi-service-app-client

      - name: Build server
        run: docker build -t youngermm/multi-service-app-server ./server

      - name: Push server
        run: docker push youngermm/multi-service-app-server

      - name: Build worker
        run: docker build -t youngermm/multi-service-app-worker ./worker

      - name: Push worker
        run: docker push youngermm/multi-service-app-worker

      - name: Build nginx
        run: docker build -t youngermm/multi-service-app-nginx ./nginx

      - name: Push nginx
        run: docker push youngermm/multi-service-app-nginx


  # deploy:
  #   name: deploy_to_render
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: JorgeLNJunior/render-deploy@v1.3.0 # Added to non-repository allow list. . .
  #     with:
  #       service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
  #       api_key: ${{ secrets.RENDER_API_KEY }} # required
  #       clear_cache: false # Clear build cache. Optional
  #       wait_deploy: false # Wait until the deploy status is successful. Warning! Free Render services can take +10 minutes to be fully deployed. Optional